
const errno = Object.freeze({
  ERR_USER_EXIST: 'ERR_USER_EXIST',
  ERR_USER_NOT_EXIST: 'ERR_USER_NOT_EXIST',
  ERR_USER_NOT_CREATED: 'ERR_USER_NOT_CREATED',
  ERR_USER_NOT_UPDATED: 'ERR_USER_NOT_UPDATED',
  ERR_USER_LOGIN_FAILED: 'ERR_USER_LOGIN_FAILED',
});

export default errno;
